#!/bin/bash
set -e

argv=()
argv[0]="-pwd$PWD"
i=1

# Preserve file paths by expanding them to absolute paths.
for arg in "$@"; do
    case "$arg" in
      -*) argv[$i]="$arg" ;;
      *)  argv[$i]="$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")" ;;
    esac
    i=$((i + 1))
done

open -a "GNAT Studio" -n -W --args "${argv[@]}"
